# Codecov configuration for code coverage reporting
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "node_modules"
  - "dist"
  - "build"
  - "coverage"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.config.js"
  - "vite.config.js"
  - "vitest.config.js"
  - "cleanup.js"
  - "start.js"
